### PR TITLE
Merge all changes from sasa1977's branch

### PR DESCRIPTION
**Pull request by aidanhs**
Hopefully nothing too terrible

### CODE REVIEW

**Comment by aidanhs** [comment]
@sasa1977 just to check you're ok with this?

**Comment by sasa1977** [comment]
Fine by me. If you think those changes are useful for others, feel free to take them :-)

**Comment by LightGuard** [comment]
Any chance we could get this pulled in? If not, I'll fork and pull into my own repo.

**Comment by aidanhs** [comment]
@LightGuard if you make any changes on top of the branch it'd be useful to make PRs back into my branch in order to keep this PR up-to-date.

If @habuma doesn't have time to maintain this, choosing one or two more actively involved people to be collaborators would be useful.

**Comment by stallio** [comment]
Definitely some good stuff here.

I have some more tweaks to add on top of these, but am a Git newb so please excuse me if I haven't gotten the hang of forking, branching, etc yet

**Comment by aidanhs** [comment]
If you fork and push the changes to your own repo, just raise an issue on my repo every now and again and I'll do the legwork of pulling in the changes to my branch.

**Comment by stallio** [comment]
Great! I've pushed a few changes here: https://github.com/stallio/asciidoc-manning-templates/tree/aphs-merge-sasa1977

**Comment by habuma** [comment]
I'm merging this PR blindly...that is I haven't tested it, nor do I have much time to test it at the moment. But feel free to try it out and if you run into any problems, send another PR to fix it and let me know so that I can merge it.

**Pull request merged**
